on:
  push:
    branches:
    # Using main for testing for now, once we are in a good spot we will switch over to release branch strategy.
      - main
    # Commented for testing
    # paths:
    #   - "terraform/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./terraform/modularized

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.10.4'

      - name: Discover Terraform subdirectories
        id: dirs
        run: |
          terraform_dirs=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u)
          echo "terraform_dirs=$terraform_dirs"
          terraform_dirs_json=$(jq -ncR '[inputs]' <<< "$terraform_dirs"
          echo "terraform_dirs=$terraform_dirs_json" >> $GITHUB_OUTPUTS

  terraform-plan:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        terraform_dir: ${{needs.setup.outputs.terraform_dirs}}
    steps:
      - name: Run init and plan
        run: |
          cd ${{matrix.terraform_dir}}
          terraform init
          terraform plan
