on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    strategy:
      matrix:
        environment: ["staging", "production"]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      - name: deploy
        run: |
          echo "deploying to ${{ matrix.environment }}"